language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: i0rlGvFmZ4yrzjUyv7HVM9YIKv4sap41zIvBHISIEAWchDTR5YazUT8hD/2Yyx4/XYWDoYhYen4aWyiZlmCJic6v0TcJVMmTqm8r8SAoDygjbxQupp3Gf2t1U1fTqtNqM1gaYte7vMm0cFP+sf9Y5JXUbPwKrt1RnrAQySoexV37mqzM/uOIBHjvfUlVKfA/pqkyKs0QTuqVK4ZFjxA04ywqlJ6MqeAe1dDrWHoSR9hTP5xlbAesfoEsG2Ih3AikncmwQINmgHGpw0ACpo0Whg+5ffQ5fL5nxUHM2bPAWM/av7mnXI3HoqGyNSjpKHv09/HOsYsnARrKbvQ5joSr4lP+nVk685QzeTj823I5B6Awj39109pYhTIEfGeTPfYDwbTZECIE7N6+qEPJKMzAOKQvvKZA4ffyIwYphOtG131lioGEsGzDSHj5UkvxUGPbD/eCw0fl8Swlvq78Bg5d3VozGkCIM/XGZGJLTEWhBWoqMHVcKC5UiQ8ja5duA2hAzWWHNzrB6dpLR7dKEBa1mToQ+sh4NvP76KRsmiP1KLt5Od8oHy2OHoxYLbhxlLNzAiGgoyZELTXYu1Bi/R7/CuX/TKs634S3mcz7mzE/EZmNsmbJHR1G6hMcqGK5rQnuKC/qx7P4EZTB77AJU3UaugUe7iMQm8SnbqSbBJ0Zr0g=
  app: founding-speeches
  on:
    repo: anhhtle/founding-speeches
